# Generated by Django 2.2.14 on 2023-06-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemId', models.IntegerField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=500)),
                ('Category', models.CharField(max_length=500)),
                ('Price', models.IntegerField()),
                ('SupplierId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('SalesId', models.IntegerField(primary_key=True, serialize=False)),
                ('StoreId', models.IntegerField()),
                ('Date', models.DateField()),
                ('ItemId', models.IntegerField()),
                ('Sales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('StoreId', models.IntegerField(primary_key=True, serialize=False)),
                ('StoreName', models.CharField(max_length=500)),
                ('StoreAddress', models.CharField(max_length=200)),
                ('StoreCapacity', models.CharField(max_length=500)),
                ('StoreManager', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierId', models.IntegerField(primary_key=True, serialize=False)),
                ('SupplierName', models.CharField(max_length=500)),
                ('SupplierContact', models.IntegerField(max_length=10)),
                ('SupplierEmail', models.CharField(max_length=500)),
                ('SupplierAddress', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('VendorId', models.IntegerField(primary_key=True, serialize=False)),
                ('VendorName', models.CharField(max_length=500)),
                ('VendorContact', models.IntegerField(max_length=10)),
                ('PayementMethod', models.CharField(max_length=500)),
                ('VendorAddress', models.CharField(max_length=500)),
            ],
        ),
    ]
