# Generated by Django 2.2.14 on 2023-06-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='SupplierContact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorContact',
            field=models.IntegerField(),
        ),
    ]
