# Generated by Django 2.2.14 on 2023-06-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_auto_20230624_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='Sales',
            new_name='SalesQty',
        ),
    ]
