# Generated by Django 2.2.14 on 2023-06-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_auto_20230625_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ItemId',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='SupplierId',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sales',
            name='ItemId',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sales',
            name='SalesId',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='SupplierId',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorId',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
