# Generated by Django 2.2.14 on 2023-06-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0007_auto_20230625_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='SalesId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
