# Generated by Django 2.2.14 on 2023-06-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0008_auto_20230626_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ItemId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='StoreId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='SupplierId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
